Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 99

AllCops:
  Exclude:
    - Gemfile
    - Rakefile
    - bin/**/*
    - config.ru
    - config/**/*
    - db/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
